version: "3.9"
services:
  web:
    container_name: shark-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/shark:ro
    tty: true
    depends_on:
      - redis
      - postgres

    ports:
      - "5001:5001"

  redis:
    image: "redis:latest"  

  postgres:
    image: postgres:12-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"